name: Bug Report
description: Report a bug with @vybe-adk/dom-element-selector
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Call `useDomElementSelector` with ...
        2. Click on ...
        3. See error ...
    validations:
      required: true

  - type: input
    id: package-version
    attributes:
      label: Package version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: react-version
    attributes:
      label: React version
      placeholder: "19.0.0"
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, screenshots, or logs.
    validations:
      required: false
